[package]
name = "overlord"
version = "0.1.0"
authors = ["Eason Gao <kaoimin@qq.com>"]
edition = "2018"
license = "MIT"
include = ["Cargo.toml", "src/*", "README.md", "LICENSE", "rust-toolchain"]
readme = "README.md"
keywords = ["consensus", "bft", "distributed-systems"]
categories = ["algorithms"]
repository = "https://github.com/cryptape/overlord"
description = """
Overlord consensus procotol.
"""

[dependencies]
async-trait = "0.1"
bit-vec = "0.6"
bytes = "0.4"
creep = "0.1"
derive_more = "0.15"
futures-preview = { version = "0.3.0-alpha.19", features = [ "async-await" ] }
futures-timer = "0.4"
log = "0.4"
log-json = { git = "https://github.com/KaoImin/log-json.git", default-features = false }
parking_lot = "0.9"
rand_core = "0.5"
rand_pcg = "0.2"
rlp = "0.4"
runtime = "0.3.0-alpha.7"
runtime-tokio = "0.3.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
bincode = "1.1"
blake2b_simd = "0.5"
crossbeam-channel = "0.3"
env_logger = "0.6"
rand = "0.6"

[features]
default = ["general"]
test = ["log-json/default"]
general = ["log-json/off"]

